### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NdaruAjaa** [Wertzui123/BedrockClans#53] opened 2023-09-24 05:03 UTC
I used the command /clan chat suddenly the server closed!

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BedrockClans

Thread: Main
Error: Wertzui123\BedrockClans\Clan::getRankColor(): Argument #1 ($rank) must be of type string, null given, called in /home/container/plugins/BedrockClans/src/Wertzui123/BedrockClans/BCPlayer.php on line 212
File: plugins/BedrockClans/src/Wertzui123/BedrockClans/Clan
Line: 431
Type: TypeError
Backtrace:
#0 plugins/BedrockClans/src/Wertzui123/BedrockClans/BCPlayer(212): Wertzui123\BedrockClans\Clan::getRankColor(null)
#1 plugins/BedrockClans/src/Wertzui123/BedrockClans/commands/subcommands/ChatSubcommand(45): Wertzui123\BedrockClans\BCPlayer->chat(string[32] dried emg devils boleh disini :v)
#2 plugins/BedrockClans/src/Wertzui123/BedrockClans/commands/ClanCommand(56): Wertzui123\BedrockClans\commands\subcommands\ChatSubcommand->execute(object pocketmine\player\Player#250643, array[6])
#3 pmsrc/src/command/SimpleCommandMap(214): Wertzui123\BedrockClans\commands\ClanCommand->execute(object pocketmine\player\Player#250643, string[4] clan, array[6])
#4 pmsrc/src/Server(1441): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#250643, string[42] clan chat dried emg devils boleh disini :v)
#5 pmsrc/src/player/Player(1515): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#250643, string[42] clan chat dried emg devils boleh disini :v)
#6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(829): pocketmine\player\Player->chat(string[43] /clan chat dried emg devils boleh disini :v)
#7 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#417540)
#8 pmsrc/src/network/mcpe/NetworkSession(495): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#238835)
#9 pmsrc/src/network/mcpe/NetworkSession(433): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#417540, string[65] M+/clan chat dried emg devils boleh disini :v..F..4..~....5j....F)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(219): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[69] s...O.I.SH.H,QH).LMQH.MWHI-..)VH..I.PH.,...T.*c......sj..-..M...10...)
#11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 1, string[78] .mTI....%N.z....hW.x.....]..J+...-..cGz.1..........d+......P%'p..".QZ....P..J.)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(111): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#179167)
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#14 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#16 pmsrc/src/Server(1707): pocketmine\snooze\SleeperHandler->sleepUntil(float 1695531704.7892)
#17 pmsrc/src/Server(1089): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#19 pmsrc/src/PocketMine(357): pocketmine\server()
#20 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Wertzui123** [comment] 2023-09-24 12:38
It looks like you aren't properly registered as a member of your clan. I don't know how this problem occurred in the first place, but you can try to leave and rejoin your clan, that might fix it.

**Comment by NdaruAjaa** [comment] 2023-09-24 12:58
Thank you, but I have made bedrock clans not crash by using clan chat false

**Comment by Wertzui123** [comment] 2023-09-24 13:41
But than you can't use the clan chat, right?

**Comment by NdaruAjaa** [comment] 2023-09-24 22:39
Yes, I just use normal chat

**Comment by Wertzui123** [comment] 2023-09-25 10:41
Sure, you can do that, but if you want to use the clan chat or investigate the issue, you can simply try rejoining the clan, as I mentioned above.

**Comment by Wertzui123** [comment] 2023-09-25 10:41
I will close this issue for now as it isn't clear to me if it was originally even caused by BedrockClans.

**Closed by Wertzui123** 2023-09-25 10:41 UTC
